# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

# rbenv
if [ -d $HOME/.rbenv ]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

# node
if [ -f $HOME/local/node/bin/node ]; then
    NODE_HOME=$HOME/local/node
    export NODE_HOME
    PATH=$NODE_HOME/bin:$PATH
    export PATH
fi
