# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos6.5-isucon3-qualifier"

  config.vm.hostname = "isucon3-qualifier"

  config.vm.network "forwarded_port", guest: 3306, host: 13306
  config.vm.network "forwarded_port", guest: 80,   host: 10080
  config.vm.network "forwarded_port", guest: 5000, host: 15000

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "./site-cookbooks"
    chef.run_list = [
                     "recipe[base]",
                     "recipe[oh-my-zsh]",
                     "recipe[mysql]",
                     "recipe[ruby]",
                     "recipe[node]",
                     "recipe[app-data]",
                     "recipe[app-ruby]",
                     "recipe[app-node]",
                     "recipe[supervisord]",
                    ]
  end

  # vagrant-omnibus
  config.omnibus.chef_version = "11.12.8"
end
